const data = [
  '<div class="zoom"><div class="he"><br/><br/><br/>כִּי-יִהְיֶה לְאִישׁ בֵּן סוֹרֵר וּמוֹרֶה, אֵינֶנּוּ שֹׁמֵעַ בְּקוֹל אָבִיו וּבְקוֹל אִמּוֹ; <span class="focus">וְיִסְּרוּ</span> אֹתוֹ, וְלֹא יִשְׁמַע אֲלֵיהֶם.</div><div class="en">If a householder has a wayward and defiant son, who does not heed his father or mother and does not obey them even after they <span class="focus">discipline</span> him…</div></div>',

  '<div class="zoom"><div class="he"><br/><br/><br/>אַשְׁרֵי הַגֶּבֶר אֲשֶׁר <span class="focus">תְּיַסְּרֶנּוּ</span> יָּהּ; וּמִתּוֹרָתְךָ תְלַמְּדֶנּוּ.</div><div class="en">Happy is the man whom You <span class="focus">discipline</span>, oh Lord,<br/>the man You instruct in Your teaching.</div>',

  '<div class="zoom focus"><div class="he">...הלך ר׳ מתיא בן חרש אצל ר׳ אלעזר הקפר ללודיא. אמר לו, רבי שמעת בארבע חלוקי כפרה שהיה ר׳ ישמאל דורש? אמר לו, כתוב אחד אומר שובו בנים שובבים, הא למדת שתשובה מכפרת, וכתוב אחד אומר כי ביום הזה מכפר עליכם, הא למדנו שיום הכפורים מכפר, וכתוב אחד אומר אם יכופר העון הזה לכם עד תמותון, הא למדת שמיתה מכפרת, וכתוב אחד אומר ופקדתי בשבט פשעם ובננעים עונם, הא למדנו שייסורין מכפרין. כיצד יתקיימו ארבעה כתובים אלו?</div><div class="en">...R’ Matia b. Heresh came before R’ Elazar HaKappar in Lydda. He said to him, my master, </br>did you hear the four types of atonement that R’ Yishma’el taught? He responded: One verse says “Repent, rebellious children” (Jeremiah 3:14); this teaches that repentance (teshuvah) atones. One verse says “For on this day you will be expiated of all of your sins” (Leviticus 16:30); this teaches that Yom Kippur atones. One verse says “Surely this iniquity will not expiated by you until you die” (Isaiah 22:14); this teaches that death atones. And one verse says “I will punish their transgressions with the rod and their sins with plagues” (Psalms 89:33); this teaches that yisurin atone.</div></div>',

  '<div class="he">...הלך ר׳ מתיא בן חרש אצל ר׳ אלעזר הקפר ללודיא. אמר לו, רבי שמעת בארבע חלוקי כפרה שהיה ר׳ ישמאל דורש? אמר לו, כתוב אחד אומר שובו בנים שובבים, הא למדת שתשובה מכפרת, וכתוב אחד אומר כי ביום הזה מכפר עליכם, הא למדנו שיום הכפורים מכפר, וכתוב אחד אומר אם יכופר העון הזה לכם עד תמותון, הא למדת שמיתה מכפרת, וכתוב אחד אומר ופקדתי בשבט פשעם ובננעים עונם, הא למדנו שייסורין מכפרין. כיצד יתקיימו ארבעה כתובים אלו?</div><div class="zoom focus"><div class="en">...R’ Matia b. Heresh came before R’ Elazar HaKappar in Lydda. He said to him, my master, </br>did you hear the four types of atonement that R’ Yishma’el taught? He responded: One verse says “Repent, rebellious children” (Jeremiah 3:14); this teaches that repentance (teshuvah) atones. One verse says “For on this day you will be expiated of all of your sins” (Leviticus 16:30); this teaches that Yom Kippur atones. One verse says “Surely this iniquity will not expiated by you until you die” (Isaiah 22:14); this teaches that death atones. And one verse says “I will punish their transgressions with the rod and their sins with plagues” (Psalms 89:33); this teaches that yisurin atone.</div></div>',

  '<div class="zoom focus"><div class="he">ר׳ נחמיה אומר, חביבין יסורין שכשם שהקורבנות מרצין, כך יסורין מרצין. בקרבנות מהו או׳: ״ונרצה לו לכפר עליו.״ בייסורין מה הוא אומר: ״הם ירצו את עונם.״ ולא עוד אלא שהייסורין מרצין יותר מהקרבנות, מפני מה, שהקרבנות בממון והיסורין בגוף.</div><div class="en">R. Nehemiah says: precious are yisurin, for just as sacrifices please (meratzin), so yisurin please (meratzin). What does it say about sacrifices? “And it shall be accepted for him (venirtzah) to make atonement for him” (Leviticus 1:4). What does it say about yisurin? “And they shall atone for (yirtzu) their iniquity” (Leviticus 26:43). And not only that, but yisurin please more than sacrifices. Why? Because sacrifices are with money but yisurin are with the body.</div>',

  '<div class="zoom focus"><div class="he">רב ששת כי הוה יתיב בתעניתא בתר דמצלי אמר הכי רבון העולמים גלוי לפניך בזמן שבית המקדש קיים אדם חוטא ומקריב קרבן ואין מקריבין ממנו אלא חלבו ודמו ומתכפר לו ועכשיו ישבתי בתענית ונתמעט חלבי ודמי יהי רצון מלפניך שיהא חלבי ודמי שנתמעט כאילו הקרבתיו לפניך על גבי המזבח ותרצני.</div><div class="en">R. Sheshet, when he was fasting, would say the following after his prayers: “Master of the Universe, it is known before You that at the time the Temple stood, a man would sin and bring an offering, and nothing but the fat and blood would be offered from it, and it would atone for him. And now I have fasted and my fat and blood have been diminished. May it be Your will that my diminished fat and blood be considered as though I offered them before You on the altar, and may they find me favor.” </div></div>',

  '<div class="he focus">רב ששת כי הוה יתיב בתעניתא בתר דמצלי אמר הכי רבון העולמים גלוי לפניך בזמן שבית המקדש קיים אדם חוטא ומקריב קרבן ואין מקריבין ממנו אלא חלבו ודמו ומתכפר לו ועכשיו ישבתי בתענית ונתמעט חלבי ודמי יהי רצון מלפניך שיהא חלבי ודמי שנתמעט כאילו הקרבתיו לפניך על גבי המזבח ותרצני.</div><div class="zoom"><div class="en focus">R. Sheshet, when he was fasting, would say the following after his prayers: “Master of the Universe, it is known before You that at the time the Temple stood, a man would sin and bring an offering, and nothing but the fat and blood would be offered from it, and it would atone for him. And now I have fasted and my fat and blood have been diminished. May it be Your will that my diminished fat and blood be considered as though I offered them before You on the altar, and may they find me favor.” </div></div>',

  '<div class="zoom"><div class="he">אמר רבא אמר רב סחורה אמר רב הונא: כל שהקב"ה חפץ בו מדכאו ביסורין שנאמר (ישעיהו נג:י) וה\' חפץ דכאו החליץ.</div><div class="en"></div><div class="he">יכול אפילו לא קבלם מאהבה?</div><div class="he">תלמוד לומר: (ישעיהו נג:י) אם תשים אשם נפשו.</div><div class="he">מה אשם לדעת אף יסורין לדעת.</div><div class="en"></div><div class="en">Rava said R. Sakhora said R. Huna said: Everyone whom the Holy-One-Blessed-Be-He favors, He afflicts with yisurin, as it is written: “Yet it pleased God to afflict him with disease” (Isaiah 53:10).</div><div class="en"></div><div class="en">Is this so even if he does not accept them out of love?</div><div class="en">No; therefore scripture states: “If his soul would offer itself in restitution (asham)” (Isaiah 53:10.). <span class="focus">Just as an asham sacrifice must be offered with the knowledge of the animals’ owners, so too yisurin must be acknowledged.</span></div></div>',

  '<div class="he">אמר רבא אמר רב סחורה אמר רב הונא: כל שהקב"ה חפץ בו מדכאו ביסורין שנאמר (ישעיהו נג:י) וה\' חפץ דכאו החליץ.</div><div class="en"></div><div class="he">יכול אפילו לא קבלם מאהבה?</div><div class="he">תלמוד לומר: (ישעיהו נג:י) אם תשים אשם נפשו.</div><div class="he">מה אשם לדעת אף יסורין לדעת.</div><div class="en"></div><div class="en">Rava said R. Sakhora said R. Huna said: Everyone whom the Holy-One-Blessed-Be-He favors, He afflicts with yisurin, as it is written: “Yet it pleased God to afflict him with disease” (Isaiah 53:10).</div><div class="en"></div><div class="zoom"><div class="en">Is this so even if he does not accept them out of love?</div><div class="en">No; therefore scripture states: “If his soul would offer itself in restitution (asham)” (Isaiah 53:10.). <span class="focus">Just as an asham sacrifice must be offered with the knowledge of the animals’ owners, so too yisurin must be acknowledged.</span></div></div><div class="en"></div>',

  '<div class="zoom"><div class="he">רבי אליעזר חלש על לגביה רבי יוחנן חזא דהוה קא גני בבית אפל גלייה לדרעיה ונפל נהורא חזייה דהוה קא בכי ר\' אליעזר א"ל אמאי קא בכית אי משום תורה דלא אפשת שנינו אחד המרבה ואחד הממעיט ובלבד שיכוין לבו לשמים ואי משום מזוני לא כל אדם זוכה לשתי שלחנות ואי משום בני דין גרמא דעשיראה ביר א"ל להאי שופרא דבלי בעפרא קא בכינא א"ל על דא ודאי קא בכית ובכו תרוייהו אדהכי והכי א"ל חביבין עליך יסורין א"ל לא הן ולא שכרן א"ל הב לי ידך יהב ליה ידיה ואוקמיה. </div><div class="en">R. Eliezer became sick. R. Yohanan came before him. He saw that R. Eliezer was lying in a dark room. He uncovered his forearm and light shone out. He saw that R. Eliezer was crying. He said to him: “Why are you crying? If it is because of the Torah that you were not able to study, have we not learned: ‘The one who does much and the one who does little are the same, as long as their intentions are for God?’ And if it is because of sustenance, not every person merits two tables. And if it is because of children, look – here is the bone of my tenth child.”</div><div class="en">R. Eliezer replied: “I am crying because of this beauty that will decompose in the earth.” He said to him: “Yes, of course you should cry about that.” And the two wept together. <span class="focus">At that point, R. Yohanan said to him: “Are your yisurin dear to you?” R. Eliezer replied: “Not them and not their reward.” R. Yohanan said to him: “Give me your hand.” He gave him his hand, and he lifted him up.</span></div></div>',

  '<div class="he">רבי אליעזר חלש על לגביה רבי יוחנן חזא דהוה קא גני בבית אפל גלייה לדרעיה ונפל נהורא חזייה דהוה קא בכי ר\' אליעזר א"ל אמאי קא בכית אי משום תורה דלא אפשת שנינו אחד המרבה ואחד הממעיט ובלבד שיכוין לבו לשמים ואי משום מזוני לא כל אדם זוכה לשתי שלחנות ואי משום בני דין גרמא דעשיראה ביר א"ל להאי שופרא דבלי בעפרא קא בכינא א"ל על דא ודאי קא בכית ובכו תרוייהו אדהכי והכי א"ל חביבין עליך יסורין א"ל לא הן ולא שכרן א"ל הב לי ידך יהב ליה ידיה ואוקמיה. </div><div class="en">R. Eliezer became sick. R. Yohanan came before him. He saw that R. Eliezer was lying in a dark room. He uncovered his forearm and light shone out. He saw that R. Eliezer was crying. He said to him: “Why are you crying? If it is because of the Torah that you were not able to study, have we not learned: ‘The one who does much and the one who does little are the same, as long as their intentions are for God?’ And if it is because of sustenance, not every person merits two tables. And if it is because of children, look – here is the bone of my tenth child.”</div><div class="en zoom">R. Eliezer replied: “I am crying because of this beauty that will decompose in the earth.” He said to him: “Yes, of course you should cry about that.” And the two wept together. <span class="focus">At that point, R. Yohanan said to him: “Are your yisurin dear to you?” R. Eliezer replied: “Not them and not their reward.” R. Yohanan said to him: “Give me your hand.” He gave him his hand, and he lifted him up.</span></div></div>',

  '<div class="zoom focus"><div class="he">עד היכן תכלית יסורין? אמר רבי אלעזר: כל שארגו לו בגד ללבוש ואין מתקבל עליו.</div><div class="en">Until what point have yisurin achieved their purpose? R’ Elazar said: Anyone who had a garment woven for him to wear and it does not fit him.</div></div><div class="he">מתקיף לה רב זעירא ואיתימא רבי שמואל בר נחמני: גדולה מזו אמרו. אפילו נתכוונו למזוג בחמין ומזגו לו בצונן בצונן ומזגו לו בחמין.</div><div class="en">R. Zeira and some say R’ Shmuel b. Nahmani objected to this: Even more than that they said! Even if he intended to mix his wine with hot water and it was mixed for him with cold, or with cold and it was mixed for him with hot.</div><div class="he">ואת אמרת כולי האי? מר בריה דרבינא אמר אפילו נהפך לו חלוקו.</div><div class="en">And you say all this?! Mar the son of Ravina said: Even if his shirt was turned backwards.</div><div class="he">רבא ואיתימא רב חסדא ואיתימא רבי יצחק ואמרי לה במתניתא תנא: אפילו הושיט ידו לכיס ליטול שלש ועלו בידו שתים. דווקא שלש ועלו בידו שתים, אבל שתים ועלו בידו שלש לא דליכא טירחא למישדייהו.</div><div class="en">Rava, or some say R’ Hisda, or some say R’ Yitzchak, or it was taught in a baraita: Even one who put his hand in his pouch to take out three coins and his hand came up with two.</div><div class="en">The baraita specifies that he intended to take out three and came up with two – but not if he intended to take out two and came up with three, because it is no trouble to him to put one back</div><div class="he">וכל כך למה? דתניא דבי רבי ישמעאל:  כל שעברו עליו ארבעים יום בלא יסורין קיבל עולמו </div><div class="en">But why all this?</div><div class="en">As it is taught in a baraita of the school of R’ Yishmael: Anyone for whom forty days passes without yisurin has “received their world” (meaning has preemptively redeemed their reward for the world to come).</div><div class="en"></div><div class="en"></div>',

  '<div class="he">עד היכן תכלית יסורין? אמר רבי אלעזר: כל שארגו לו בגד ללבוש ואין מתקבל עליו.</div><div class="en">Until what point have yisurin achieved their purpose? R’ Elazar said: Anyone who had a garment woven for him to wear and it does not fit him.</div><div class="zoom focus"><div class="he">מתקיף לה רב זעירא ואיתימא רבי שמואל בר נחמני: גדולה מזו אמרו. אפילו נתכוונו למזוג בחמין ומזגו לו בצונן בצונן ומזגו לו בחמין.</div><div class="en">R. Zeira and some say R’ Shmuel b. Nahmani objected to this: Even more than that they said! Even if he intended to mix his wine with hot water and it was mixed for him with cold, or with cold and it was mixed for him with hot.</div></div><div class="he">ואת אמרת כולי האי? מר בריה דרבינא אמר אפילו נהפך לו חלוקו.</div><div class="en">And you say all this?! Mar the son of Ravina said: Even if his shirt was turned backwards.</div><div class="he">רבא ואיתימא רב חסדא ואיתימא רבי יצחק ואמרי לה במתניתא תנא: אפילו הושיט ידו לכיס ליטול שלש ועלו בידו שתים. דווקא שלש ועלו בידו שתים, אבל שתים ועלו בידו שלש לא דליכא טירחא למישדייהו.</div><div class="en">Rava, or some say R’ Hisda, or some say R’ Yitzchak, or it was taught in a baraita: Even one who put his hand in his pouch to take out three coins and his hand came up with two.</div><div class="en">The baraita specifies that he intended to take out three and came up with two – but not if he intended to take out two and came up with three, because it is no trouble to him to put one back</div><div class="he">וכל כך למה? דתניא דבי רבי ישמעאל:  כל שעברו עליו ארבעים יום בלא יסורין קיבל עולמו </div><div class="en">But why all this?</div><div class="en">As it is taught in a baraita of the school of R’ Yishmael: Anyone for whom forty days passes without yisurin has “received their world” (meaning has preemptively redeemed their reward for the world to come).</div>',

  '<div class="he">עד היכן תכלית יסורין? אמר רבי אלעזר: כל שארגו לו בגד ללבוש ואין מתקבל עליו.</div><div class="en">Until what point have yisurin achieved their purpose? R’ Elazar said: Anyone who had a garment woven for him to wear and it does not fit him.</div><div class="he">מתקיף לה רב זעירא ואיתימא רבי שמואל בר נחמני: גדולה מזו אמרו. אפילו נתכוונו למזוג בחמין ומזגו לו בצונן בצונן ומזגו לו בחמין.</div><div class="en">R. Zeira and some say R’ Shmuel b. Nahmani objected to this: Even more than that they said! Even if he intended to mix his wine with hot water and it was mixed for him with cold, or with cold and it was mixed for him with hot.</div><div class="zoom focus"><div class="he">ואת אמרת כולי האי? מר בריה דרבינא אמר אפילו נהפך לו חלוקו.</div><div class="en">And you say all this?! Mar the son of Ravina said: Even if his shirt was turned backwards.</div></div><div class="he">רבא ואיתימא רב חסדא ואיתימא רבי יצחק ואמרי לה במתניתא תנא: אפילו הושיט ידו לכיס ליטול שלש ועלו בידו שתים. דווקא שלש ועלו בידו שתים, אבל שתים ועלו בידו שלש לא דליכא טירחא למישדייהו.</div><div class="en">Rava, or some say R’ Hisda, or some say R’ Yitzchak, or it was taught in a baraita: Even one who put his hand in his pouch to take out three coins and his hand came up with two.</div><div class="en">The baraita specifies that he intended to take out three and came up with two – but not if he intended to take out two and came up with three, because it is no trouble to him to put one back</div><div class="he">וכל כך למה? דתניא דבי רבי ישמעאל:  כל שעברו עליו ארבעים יום בלא יסורין קיבל עולמו </div><div class="en">But why all this?</div><div class="en">As it is taught in a baraita of the school of R’ Yishmael: Anyone for whom forty days passes without yisurin has “received their world” (meaning has preemptively redeemed their reward for the world to come).</div><div class="en"></div><div class="en"></div>',

  '<div class="he">עד היכן תכלית יסורין? אמר רבי אלעזר: כל שארגו לו בגד ללבוש ואין מתקבל עליו.</div><div class="en">Until what point have yisurin achieved their purpose? R’ Elazar said: Anyone who had a garment woven for him to wear and it does not fit him.</div><div class="he">מתקיף לה רב זעירא ואיתימא רבי שמואל בר נחמני: גדולה מזו אמרו. אפילו נתכוונו למזוג בחמין ומזגו לו בצונן בצונן ומזגו לו בחמין.</div><div class="en">R. Zeira and some say R’ Shmuel b. Nahmani objected to this: Even more than that they said! Even if he intended to mix his wine with hot water and it was mixed for him with cold, or with cold and it was mixed for him with hot.</div><div class="he">ואת אמרת כולי האי? מר בריה דרבינא אמר אפילו נהפך לו חלוקו.</div><div class="en">And you say all this?! Mar the son of Ravina said: Even if his shirt was turned backwards.</div><div class="zoom focus"><div class="he">רבא ואיתימא רב חסדא ואיתימא רבי יצחק ואמרי לה במתניתא תנא: אפילו הושיט ידו לכיס ליטול שלש ועלו בידו שתים. דווקא שלש ועלו בידו שתים, אבל שתים ועלו בידו שלש לא דליכא טירחא למישדייהו.</div><div class="en">Rava, or some say R’ Hisda, or some say R’ Yitzchak, or it was taught in a baraita: Even one who put his hand in his pouch to take out three coins and his hand came up with two.</div><div class="en">The baraita specifies that he intended to take out three and came up with two – but not if he intended to take out two and came up with three, because it is no trouble to him to put one back</div></div><div class="he">וכל כך למה? דתניא דבי רבי ישמעאל:  כל שעברו עליו ארבעים יום בלא יסורין קיבל עולמו </div><div class="en">But why all this?</div><div class="en">As it is taught in a baraita of the school of R’ Yishmael: Anyone for whom forty days passes without yisurin has “received their world” (meaning has preemptively redeemed their reward for the world to come).</div><div class="en"></div><div class="en"></div>',

  '<div class="he">עד היכן תכלית יסורין? אמר רבי אלעזר: כל שארגו לו בגד ללבוש ואין מתקבל עליו.</div><div class="en">Until what point have yisurin achieved their purpose? R’ Elazar said: Anyone who had a garment woven for him to wear and it does not fit him.</div><div class="he">מתקיף לה רב זעירא ואיתימא רבי שמואל בר נחמני: גדולה מזו אמרו. אפילו נתכוונו למזוג בחמין ומזגו לו בצונן בצונן ומזגו לו בחמין.</div><div class="en">R. Zeira and some say R’ Shmuel b. Nahmani objected to this: Even more than that they said! Even if he intended to mix his wine with hot water and it was mixed for him with cold, or with cold and it was mixed for him with hot.</div><div class="he">ואת אמרת כולי האי? מר בריה דרבינא אמר אפילו נהפך לו חלוקו.</div><div class="en">And you say all this?! Mar the son of Ravina said: Even if his shirt was turned backwards.</div><div class="he">רבא ואיתימא רב חסדא ואיתימא רבי יצחק ואמרי לה במתניתא תנא: אפילו הושיט ידו לכיס ליטול שלש ועלו בידו שתים. דווקא שלש ועלו בידו שתים, אבל שתים ועלו בידו שלש לא דליכא טירחא למישדייהו.</div><div class="en">Rava, or some say R’ Hisda, or some say R’ Yitzchak, or it was taught in a baraita: Even one who put his hand in his pouch to take out three coins and his hand came up with two.</div><div class="en">The baraita specifies that he intended to take out three and came up with two – but not if he intended to take out two and came up with three, because it is no trouble to him to put one back</div><div class="zoom focus"><div class="he">וכל כך למה? דתניא דבי רבי ישמעאל:  כל שעברו עליו ארבעים יום בלא יסורין קיבל עולמו </div><div class="en">But why all this?</div><div class="en">As it is taught in a baraita of the school of R’ Yishmael: Anyone for whom forty days passes without yisurin has “received their world” (meaning has preemptively redeemed their reward for the world to come).</div><div class="en"></div><div class="en"></div></div>'

]

const data2 = ['<strong>I. Yisurin in Tanakh</strong></br>1. דברים כא:יח</br>Deuteronomy 21:18         </br></br>',

'<strong>I. Yisurin in Tanakh</strong></br>2. תהילים צד:יב</br>Psalms 94:12         </br></br>',

'<strong>II. Yisurin in Tannaitic Literature</strong></br>1. מכילתא דר״י יתרו דבחדש ז</br>Mekhilta de-Rabbi Ishmael, Yitro Debachodesh 7</br> ',

'<strong>II. Yisurin in Tannaitic Literature</strong></br>1. מכילתא דר״י יתרו דבחדש ז</br>Mekhilta de-Rabbi Ishmael, Yitro Debachodesh 7</br> ',

'<strong>II. Yisurin in Tannaitic Literature</strong></br>2. מכילתא דר״י יתרו דבחדש י</br>Mekhilta de-Rabbi Ishmael, Yitro Debachodesh 10</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>1. בבלי ברכות י״ז ע״א</br>Talmud Bavli Berachot 17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>1. בבלי ברכות י״ז ע״א</br>Talmud Bavli Berachot 17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>2. בבלי ברכות ה ע״א</br>Talmud Bavli Berachot 5a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>2. בבלי ברכות ה ע״א</br>Talmud Bavli Berachot 5a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>3. בבלי ברכות ה ע״ב</br>Talmud Bavli Berachot 5b</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>3. בבלי ברכות ה ע״ב</br>Talmud Bavli Berachot 5b</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>4. בבלי ערכין ט״ז ע״ב-י״ז ע״א</br>Talmud Bavli Arakhin 16b-17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>4. בבלי ערכין ט״ז ע״ב-י״ז ע״א</br>Talmud Bavli Arakhin 16b-17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>4. בבלי ערכין ט״ז ע״ב-י״ז ע״א</br>Talmud Bavli Arakhin 16b-17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>4. בבלי ערכין ט״ז ע״ב-י״ז ע״א</br>Talmud Bavli Arakhin 16b-17a</br> ',

'<strong>III. Yisurin in the Bavli</strong></br>4. בבלי ערכין ט״ז ע״ב-י״ז ע״א</br>Talmud Bavli Arakhin 16b-17a</br> '

]
